[package]
name = "game_scene"
version = "0.1.0"
edition = "2021"

[dependencies]
avian3d = "0.1.0"
bevy = { version = "0.14.0", features = ["dynamic_linking"] }
game_camera = { version = "0.1.0", path = "../game_camera" }
